export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO' 
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR' 

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS' 
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGAR_PRODUCTOS_ERROR' 
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGAR_PRODUCTOS_EXITO' 
